/shared_controller/shared_controller:
  ros__parameters:
    cluster_topic: "/dwal_planner/clusters_near"
    user_cmd_topic: "/user_cmd" #"/cmd_vel_web"
    output_cmd_topic: "/cmd_vel"
    odom_topic: "/odom"
    joy_topic: "/joy_web"
    r2_button_index: 7
    use_stamped_twist_input: true
    use_stamped_twist_output: true

    v_low: 0.25         # clusers hysteresis low threshold (m/s)
    v_high: 0.35       # clusters hysteresis high threshold (m/s) 

    c_max: 255.0        # cost normalization denominator (Nav2 costmap max typically 255)
    alpha: 0.7          # (0,1] higher -> follow user intent more, lower -> prioritize safety cost more
    s_min: 0.2          # (0,1] minimum speed scaling in velocity damping
    Kphi: 1.5           # scale of w->phi    
    Kmax: 4.0           # max curvature in DWAL                   ===> CROSS CHECK IN DWAL YAML ALSO!!!!